InternalClassType: DataTable
Coordinate3D: [-14.5,-6,0]
Name: ProductRanges
Origin: d6a75ee0-8e9e-4c40-a584-1111ec6c6863
UUID: 3e943420-305b-45e6-9598-ebf162c4bf8d
3D:
 Rotation: [0,0,0,-1]
$Data:
 ListFormat:
  ColumnIndex: true
  ColumnWidth: 20
  DataType: string
  MaxXDim: 4
  ShowDataType: true
  ColumnFormat:
  -
   Index: 1
   Width: 30
  -
   Index: 2
   DataType: string
   Width: 18
  -
   Index: 3
   DataType: integer
   Width: 8
  -
   Index: 4
   DataType: integer
   Width: 7
  RowFormat:
  -
   Index: 0
   Hidden: false
 ColumnIndex: [string,5,~,"Product","Racklane","From","To"]
 Columns:
