InternalClassType: DataTable
Origin: 01f9b88d-3e67-4711-91f8-39419ecdccf8
UUID: 0fd17a3f-fdfb-49f7-b5e1-ea90bd63715c
$CustomAttributes:
-
 Name: OnOpen
 $DataType: method
 RandomSeed: 1073886640
-
 Name: OnClose
 $DataType: method
 RandomSeed: 1073886638
$Data:
